// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.FinCtrlNum;
import com.tuc.capacity.entity.mstr.FinCtrlNumDataOnDemand;
import com.tuc.capacity.entity.mstr.FinCtrlNumIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FinCtrlNumIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FinCtrlNumIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FinCtrlNumIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FinCtrlNumIntegrationTest: @Transactional;
    
    @Autowired
    FinCtrlNumDataOnDemand FinCtrlNumIntegrationTest.dod;
    
    @Test
    public void FinCtrlNumIntegrationTest.testCountFinCtrlNums() {
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to initialize correctly", dod.getRandomFinCtrlNum());
        long count = FinCtrlNum.countFinCtrlNums();
        Assert.assertTrue("Counter for 'FinCtrlNum' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FinCtrlNumIntegrationTest.testFindFinCtrlNum() {
        FinCtrlNum obj = dod.getRandomFinCtrlNum();
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to provide an identifier", id);
        obj = FinCtrlNum.findFinCtrlNum(id);
        Assert.assertNotNull("Find method for 'FinCtrlNum' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FinCtrlNum' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FinCtrlNumIntegrationTest.testFindAllFinCtrlNums() {
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to initialize correctly", dod.getRandomFinCtrlNum());
        long count = FinCtrlNum.countFinCtrlNums();
        Assert.assertTrue("Too expensive to perform a find all test for 'FinCtrlNum', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FinCtrlNum> result = FinCtrlNum.findAllFinCtrlNums();
        Assert.assertNotNull("Find all method for 'FinCtrlNum' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FinCtrlNum' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FinCtrlNumIntegrationTest.testFindFinCtrlNumEntries() {
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to initialize correctly", dod.getRandomFinCtrlNum());
        long count = FinCtrlNum.countFinCtrlNums();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FinCtrlNum> result = FinCtrlNum.findFinCtrlNumEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FinCtrlNum' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FinCtrlNum' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FinCtrlNumIntegrationTest.testFlush() {
        FinCtrlNum obj = dod.getRandomFinCtrlNum();
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to provide an identifier", id);
        obj = FinCtrlNum.findFinCtrlNum(id);
        Assert.assertNotNull("Find method for 'FinCtrlNum' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFinCtrlNum(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FinCtrlNum' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FinCtrlNumIntegrationTest.testMergeUpdate() {
        FinCtrlNum obj = dod.getRandomFinCtrlNum();
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to provide an identifier", id);
        obj = FinCtrlNum.findFinCtrlNum(id);
        boolean modified =  dod.modifyFinCtrlNum(obj);
        Integer currentVersion = obj.getVersion();
        FinCtrlNum merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FinCtrlNum' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FinCtrlNumIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to initialize correctly", dod.getRandomFinCtrlNum());
        FinCtrlNum obj = dod.getNewTransientFinCtrlNum(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FinCtrlNum' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'FinCtrlNum' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FinCtrlNumIntegrationTest.testRemove() {
        FinCtrlNum obj = dod.getRandomFinCtrlNum();
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinCtrlNum' failed to provide an identifier", id);
        obj = FinCtrlNum.findFinCtrlNum(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FinCtrlNum' with identifier '" + id + "'", FinCtrlNum.findFinCtrlNum(id));
    }
    
}
