// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.FinCtrlNumDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FinCtrlNumDataOnDemand_Roo_Configurable {
    
    declare @type: FinCtrlNumDataOnDemand: @Configurable;
    
}
