// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.Sow;
import com.tuc.capacity.entity.SowDataOnDemand;
import com.tuc.capacity.entity.mstr.FinCtrlNum;
import com.tuc.capacity.entity.mstr.FinCtrlNumDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FinCtrlNumDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FinCtrlNumDataOnDemand: @Component;
    
    private Random FinCtrlNumDataOnDemand.rnd = new SecureRandom();
    
    private List<FinCtrlNum> FinCtrlNumDataOnDemand.data;
    
    @Autowired
    SowDataOnDemand FinCtrlNumDataOnDemand.sowDataOnDemand;
    
    public FinCtrlNum FinCtrlNumDataOnDemand.getNewTransientFinCtrlNum(int index) {
        FinCtrlNum obj = new FinCtrlNum();
        setFinCtrlNum(obj, index);
        setSow(obj, index);
        return obj;
    }
    
    public void FinCtrlNumDataOnDemand.setFinCtrlNum(FinCtrlNum obj, int index) {
        String finCtrlNum = "finCtrlNum_" + index;
        obj.setFinCtrlNum(finCtrlNum);
    }
    
    public void FinCtrlNumDataOnDemand.setSow(FinCtrlNum obj, int index) {
        Sow sow = sowDataOnDemand.getRandomSow();
        obj.setSow(sow);
    }
    
    public FinCtrlNum FinCtrlNumDataOnDemand.getSpecificFinCtrlNum(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FinCtrlNum obj = data.get(index);
        Long id = obj.getId();
        return FinCtrlNum.findFinCtrlNum(id);
    }
    
    public FinCtrlNum FinCtrlNumDataOnDemand.getRandomFinCtrlNum() {
        init();
        FinCtrlNum obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return FinCtrlNum.findFinCtrlNum(id);
    }
    
    public boolean FinCtrlNumDataOnDemand.modifyFinCtrlNum(FinCtrlNum obj) {
        return false;
    }
    
    public void FinCtrlNumDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FinCtrlNum.findFinCtrlNumEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FinCtrlNum' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FinCtrlNum>();
        for (int i = 0; i < 10; i++) {
            FinCtrlNum obj = getNewTransientFinCtrlNum(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
