// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.ProjectRole;
import com.tuc.capacity.entity.mstr.ProjectRoleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProjectRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectRoleDataOnDemand: @Component;
    
    private Random ProjectRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<ProjectRole> ProjectRoleDataOnDemand.data;
    
    public ProjectRole ProjectRoleDataOnDemand.getNewTransientProjectRole(int index) {
        ProjectRole obj = new ProjectRole();
        setRoleName(obj, index);
        return obj;
    }
    
    public void ProjectRoleDataOnDemand.setRoleName(ProjectRole obj, int index) {
        String roleName = "roleName_" + index;
        obj.setRoleName(roleName);
    }
    
    public ProjectRole ProjectRoleDataOnDemand.getSpecificProjectRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProjectRole obj = data.get(index);
        Long id = obj.getId();
        return ProjectRole.findProjectRole(id);
    }
    
    public ProjectRole ProjectRoleDataOnDemand.getRandomProjectRole() {
        init();
        ProjectRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProjectRole.findProjectRole(id);
    }
    
    public boolean ProjectRoleDataOnDemand.modifyProjectRole(ProjectRole obj) {
        return false;
    }
    
    public void ProjectRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProjectRole.findProjectRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProjectRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProjectRole>();
        for (int i = 0; i < 10; i++) {
            ProjectRole obj = getNewTransientProjectRole(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
