// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.Rate;
import com.tuc.capacity.entity.mstr.RateDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RateDataOnDemand: @Component;
    
    private Random RateDataOnDemand.rnd = new SecureRandom();
    
    private List<Rate> RateDataOnDemand.data;
    
    public Rate RateDataOnDemand.getNewTransientRate(int index) {
        Rate obj = new Rate();
        setName(obj, index);
        setRate(obj, index);
        return obj;
    }
    
    public void RateDataOnDemand.setName(Rate obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void RateDataOnDemand.setRate(Rate obj, int index) {
        Integer rate = new Integer(index);
        obj.setRate(rate);
    }
    
    public Rate RateDataOnDemand.getSpecificRate(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Rate obj = data.get(index);
        Long id = obj.getId();
        return Rate.findRate(id);
    }
    
    public Rate RateDataOnDemand.getRandomRate() {
        init();
        Rate obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Rate.findRate(id);
    }
    
    public boolean RateDataOnDemand.modifyRate(Rate obj) {
        return false;
    }
    
    public void RateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Rate.findRateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Rate' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Rate>();
        for (int i = 0; i < 10; i++) {
            Rate obj = getNewTransientRate(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
