// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.Rate;
import com.tuc.capacity.entity.mstr.RateDataOnDemand;
import com.tuc.capacity.entity.mstr.RateIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RateIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RateIntegrationTest: @Transactional;
    
    @Autowired
    RateDataOnDemand RateIntegrationTest.dod;
    
    @Test
    public void RateIntegrationTest.testCountRates() {
        Assert.assertNotNull("Data on demand for 'Rate' failed to initialize correctly", dod.getRandomRate());
        long count = Rate.countRates();
        Assert.assertTrue("Counter for 'Rate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RateIntegrationTest.testFindRate() {
        Rate obj = dod.getRandomRate();
        Assert.assertNotNull("Data on demand for 'Rate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rate' failed to provide an identifier", id);
        obj = Rate.findRate(id);
        Assert.assertNotNull("Find method for 'Rate' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Rate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RateIntegrationTest.testFindAllRates() {
        Assert.assertNotNull("Data on demand for 'Rate' failed to initialize correctly", dod.getRandomRate());
        long count = Rate.countRates();
        Assert.assertTrue("Too expensive to perform a find all test for 'Rate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Rate> result = Rate.findAllRates();
        Assert.assertNotNull("Find all method for 'Rate' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Rate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RateIntegrationTest.testFindRateEntries() {
        Assert.assertNotNull("Data on demand for 'Rate' failed to initialize correctly", dod.getRandomRate());
        long count = Rate.countRates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Rate> result = Rate.findRateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Rate' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Rate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RateIntegrationTest.testFlush() {
        Rate obj = dod.getRandomRate();
        Assert.assertNotNull("Data on demand for 'Rate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rate' failed to provide an identifier", id);
        obj = Rate.findRate(id);
        Assert.assertNotNull("Find method for 'Rate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRate(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Rate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RateIntegrationTest.testMergeUpdate() {
        Rate obj = dod.getRandomRate();
        Assert.assertNotNull("Data on demand for 'Rate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rate' failed to provide an identifier", id);
        obj = Rate.findRate(id);
        boolean modified =  dod.modifyRate(obj);
        Integer currentVersion = obj.getVersion();
        Rate merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Rate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Rate' failed to initialize correctly", dod.getRandomRate());
        Rate obj = dod.getNewTransientRate(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Rate' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Rate' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Rate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RateIntegrationTest.testRemove() {
        Rate obj = dod.getRandomRate();
        Assert.assertNotNull("Data on demand for 'Rate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rate' failed to provide an identifier", id);
        obj = Rate.findRate(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Rate' with identifier '" + id + "'", Rate.findRate(id));
    }
    
}
