// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.Location;

privileged aspect Location_Roo_JavaBean {
    
    public String Location.getLocation() {
        return this.location;
    }
    
    public void Location.setLocation(String location) {
        this.location = location;
    }
    
}
