// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.ProjectRole;

privileged aspect ProjectRole_Roo_JavaBean {
    
    public String ProjectRole.getRoleName() {
        return this.roleName;
    }
    
    public void ProjectRole.setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
}
