// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.ProjectType;

privileged aspect ProjectType_Roo_JavaBean {
    
    public String ProjectType.getType() {
        return this.type;
    }
    
    public void ProjectType.setType(String type) {
        this.type = type;
    }
    
}
