// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity.mstr;

import com.tuc.capacity.entity.mstr.Skill;

privileged aspect Skill_Roo_JavaBean {
    
    public String Skill.getSkillName() {
        return this.skillName;
    }
    
    public void Skill.setSkillName(String skillName) {
        this.skillName = skillName;
    }
    
}
