// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.TuLead;

privileged aspect TuLead_Roo_JavaBean {
    
    public String TuLead.getName() {
        return this.name;
    }
    
    public void TuLead.setName(String name) {
        this.name = name;
    }
    
}
