// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.Associate;
import com.tuc.capacity.entity.AssociateDataOnDemand;
import com.tuc.capacity.entity.AssociateIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AssociateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AssociateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AssociateIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AssociateIntegrationTest: @Transactional;
    
    @Autowired
    AssociateDataOnDemand AssociateIntegrationTest.dod;
    
    @Test
    public void AssociateIntegrationTest.testCountAssociates() {
        Assert.assertNotNull("Data on demand for 'Associate' failed to initialize correctly", dod.getRandomAssociate());
        long count = Associate.countAssociates();
        Assert.assertTrue("Counter for 'Associate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AssociateIntegrationTest.testFindAssociate() {
        Associate obj = dod.getRandomAssociate();
        Assert.assertNotNull("Data on demand for 'Associate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Associate' failed to provide an identifier", id);
        obj = Associate.findAssociate(id);
        Assert.assertNotNull("Find method for 'Associate' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Associate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AssociateIntegrationTest.testFindAllAssociates() {
        Assert.assertNotNull("Data on demand for 'Associate' failed to initialize correctly", dod.getRandomAssociate());
        long count = Associate.countAssociates();
        Assert.assertTrue("Too expensive to perform a find all test for 'Associate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Associate> result = Associate.findAllAssociates();
        Assert.assertNotNull("Find all method for 'Associate' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Associate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AssociateIntegrationTest.testFindAssociateEntries() {
        Assert.assertNotNull("Data on demand for 'Associate' failed to initialize correctly", dod.getRandomAssociate());
        long count = Associate.countAssociates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Associate> result = Associate.findAssociateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Associate' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Associate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AssociateIntegrationTest.testFlush() {
        Associate obj = dod.getRandomAssociate();
        Assert.assertNotNull("Data on demand for 'Associate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Associate' failed to provide an identifier", id);
        obj = Associate.findAssociate(id);
        Assert.assertNotNull("Find method for 'Associate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAssociate(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Associate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AssociateIntegrationTest.testMergeUpdate() {
        Associate obj = dod.getRandomAssociate();
        Assert.assertNotNull("Data on demand for 'Associate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Associate' failed to provide an identifier", id);
        obj = Associate.findAssociate(id);
        boolean modified =  dod.modifyAssociate(obj);
        Integer currentVersion = obj.getVersion();
        Associate merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Associate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AssociateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Associate' failed to initialize correctly", dod.getRandomAssociate());
        Associate obj = dod.getNewTransientAssociate(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Associate' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Associate' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Associate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AssociateIntegrationTest.testRemove() {
        Associate obj = dod.getRandomAssociate();
        Assert.assertNotNull("Data on demand for 'Associate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Associate' failed to provide an identifier", id);
        obj = Associate.findAssociate(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Associate' with identifier '" + id + "'", Associate.findAssociate(id));
    }
    
}
