// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.ProjectAllocation;
import com.tuc.capacity.entity.ProjectAllocationDataOnDemand;
import com.tuc.capacity.entity.ProjectAllocationIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProjectAllocationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProjectAllocationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProjectAllocationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProjectAllocationIntegrationTest: @Transactional;
    
    @Autowired
    ProjectAllocationDataOnDemand ProjectAllocationIntegrationTest.dod;
    
    @Test
    public void ProjectAllocationIntegrationTest.testCountProjectAllocations() {
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to initialize correctly", dod.getRandomProjectAllocation());
        long count = ProjectAllocation.countProjectAllocations();
        Assert.assertTrue("Counter for 'ProjectAllocation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProjectAllocationIntegrationTest.testFindProjectAllocation() {
        ProjectAllocation obj = dod.getRandomProjectAllocation();
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to provide an identifier", id);
        obj = ProjectAllocation.findProjectAllocation(id);
        Assert.assertNotNull("Find method for 'ProjectAllocation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProjectAllocation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProjectAllocationIntegrationTest.testFindAllProjectAllocations() {
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to initialize correctly", dod.getRandomProjectAllocation());
        long count = ProjectAllocation.countProjectAllocations();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProjectAllocation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProjectAllocation> result = ProjectAllocation.findAllProjectAllocations();
        Assert.assertNotNull("Find all method for 'ProjectAllocation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProjectAllocation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProjectAllocationIntegrationTest.testFindProjectAllocationEntries() {
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to initialize correctly", dod.getRandomProjectAllocation());
        long count = ProjectAllocation.countProjectAllocations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProjectAllocation> result = ProjectAllocation.findProjectAllocationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProjectAllocation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProjectAllocation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProjectAllocationIntegrationTest.testFlush() {
        ProjectAllocation obj = dod.getRandomProjectAllocation();
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to provide an identifier", id);
        obj = ProjectAllocation.findProjectAllocation(id);
        Assert.assertNotNull("Find method for 'ProjectAllocation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProjectAllocation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProjectAllocation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectAllocationIntegrationTest.testMergeUpdate() {
        ProjectAllocation obj = dod.getRandomProjectAllocation();
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to provide an identifier", id);
        obj = ProjectAllocation.findProjectAllocation(id);
        boolean modified =  dod.modifyProjectAllocation(obj);
        Integer currentVersion = obj.getVersion();
        ProjectAllocation merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProjectAllocation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectAllocationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to initialize correctly", dod.getRandomProjectAllocation());
        ProjectAllocation obj = dod.getNewTransientProjectAllocation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProjectAllocation' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProjectAllocation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProjectAllocationIntegrationTest.testRemove() {
        ProjectAllocation obj = dod.getRandomProjectAllocation();
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProjectAllocation' failed to provide an identifier", id);
        obj = ProjectAllocation.findProjectAllocation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProjectAllocation' with identifier '" + id + "'", ProjectAllocation.findProjectAllocation(id));
    }
    
}
