// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.ProjectGroup;
import com.tuc.capacity.entity.ProjectGroupDataOnDemand;
import com.tuc.capacity.entity.TuLead;
import com.tuc.capacity.entity.TuLeadDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProjectGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectGroupDataOnDemand: @Component;
    
    private Random ProjectGroupDataOnDemand.rnd = new SecureRandom();
    
    private List<ProjectGroup> ProjectGroupDataOnDemand.data;
    
    @Autowired
    TuLeadDataOnDemand ProjectGroupDataOnDemand.tuLeadDataOnDemand;
    
    public ProjectGroup ProjectGroupDataOnDemand.getNewTransientProjectGroup(int index) {
        ProjectGroup obj = new ProjectGroup();
        setLead(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void ProjectGroupDataOnDemand.setLead(ProjectGroup obj, int index) {
        TuLead lead = tuLeadDataOnDemand.getRandomTuLead();
        obj.setLead(lead);
    }
    
    public void ProjectGroupDataOnDemand.setName(ProjectGroup obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ProjectGroup ProjectGroupDataOnDemand.getSpecificProjectGroup(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProjectGroup obj = data.get(index);
        Long id = obj.getId();
        return ProjectGroup.findProjectGroup(id);
    }
    
    public ProjectGroup ProjectGroupDataOnDemand.getRandomProjectGroup() {
        init();
        ProjectGroup obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProjectGroup.findProjectGroup(id);
    }
    
    public boolean ProjectGroupDataOnDemand.modifyProjectGroup(ProjectGroup obj) {
        return false;
    }
    
    public void ProjectGroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProjectGroup.findProjectGroupEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProjectGroup' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProjectGroup>();
        for (int i = 0; i < 10; i++) {
            ProjectGroup obj = getNewTransientProjectGroup(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
