// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.Project;
import com.tuc.capacity.entity.ProjectDataOnDemand;
import com.tuc.capacity.entity.ProjectGroup;
import com.tuc.capacity.entity.ProjectGroupDataOnDemand;
import com.tuc.capacity.entity.TuLead;
import com.tuc.capacity.entity.TuLeadDataOnDemand;
import com.tuc.capacity.entity.mstr.ProjectType;
import com.tuc.capacity.entity.mstr.ProjectTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProjectDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectDataOnDemand: @Component;
    
    private Random ProjectDataOnDemand.rnd = new SecureRandom();
    
    private List<Project> ProjectDataOnDemand.data;
    
    @Autowired
    TuLeadDataOnDemand ProjectDataOnDemand.tuLeadDataOnDemand;
    
    @Autowired
    ProjectGroupDataOnDemand ProjectDataOnDemand.projectGroupDataOnDemand;
    
    @Autowired
    ProjectTypeDataOnDemand ProjectDataOnDemand.projectTypeDataOnDemand;
    
    public Project ProjectDataOnDemand.getNewTransientProject(int index) {
        Project obj = new Project();
        setLead(obj, index);
        setName(obj, index);
        setPrjGroup(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void ProjectDataOnDemand.setLead(Project obj, int index) {
        TuLead lead = tuLeadDataOnDemand.getRandomTuLead();
        obj.setLead(lead);
    }
    
    public void ProjectDataOnDemand.setName(Project obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ProjectDataOnDemand.setPrjGroup(Project obj, int index) {
        ProjectGroup prjGroup = projectGroupDataOnDemand.getRandomProjectGroup();
        obj.setPrjGroup(prjGroup);
    }
    
    public void ProjectDataOnDemand.setType(Project obj, int index) {
        ProjectType type = projectTypeDataOnDemand.getRandomProjectType();
        obj.setType(type);
    }
    
    public Project ProjectDataOnDemand.getSpecificProject(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Project obj = data.get(index);
        Long id = obj.getId();
        return Project.findProject(id);
    }
    
    public Project ProjectDataOnDemand.getRandomProject() {
        init();
        Project obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Project.findProject(id);
    }
    
    public boolean ProjectDataOnDemand.modifyProject(Project obj) {
        return false;
    }
    
    public void ProjectDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Project.findProjectEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Project' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Project>();
        for (int i = 0; i < 10; i++) {
            Project obj = getNewTransientProject(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
