// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.Associate;
import com.tuc.capacity.entity.AssociateDataOnDemand;
import com.tuc.capacity.entity.Sow;
import com.tuc.capacity.entity.SowAllocation;
import com.tuc.capacity.entity.SowAllocationDataOnDemand;
import com.tuc.capacity.entity.SowDataOnDemand;
import com.tuc.capacity.entity.mstr.FinCtrlNum;
import com.tuc.capacity.entity.mstr.FinCtrlNumDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SowAllocationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SowAllocationDataOnDemand: @Component;
    
    private Random SowAllocationDataOnDemand.rnd = new SecureRandom();
    
    private List<SowAllocation> SowAllocationDataOnDemand.data;
    
    @Autowired
    AssociateDataOnDemand SowAllocationDataOnDemand.associateDataOnDemand;
    
    @Autowired
    FinCtrlNumDataOnDemand SowAllocationDataOnDemand.finCtrlNumDataOnDemand;
    
    @Autowired
    SowDataOnDemand SowAllocationDataOnDemand.sowDataOnDemand;
    
    public SowAllocation SowAllocationDataOnDemand.getNewTransientSowAllocation(int index) {
        SowAllocation obj = new SowAllocation();
        setAssociate(obj, index);
        setFinCtrlNum(obj, index);
        setSow(obj, index);
        return obj;
    }
    
    public void SowAllocationDataOnDemand.setAssociate(SowAllocation obj, int index) {
        Associate associate = associateDataOnDemand.getRandomAssociate();
        obj.setAssociate(associate);
    }
    
    public void SowAllocationDataOnDemand.setFinCtrlNum(SowAllocation obj, int index) {
        FinCtrlNum finCtrlNum = finCtrlNumDataOnDemand.getRandomFinCtrlNum();
        obj.setFinCtrlNum(finCtrlNum);
    }
    
    public void SowAllocationDataOnDemand.setSow(SowAllocation obj, int index) {
        Sow sow = sowDataOnDemand.getRandomSow();
        obj.setSow(sow);
    }
    
    public SowAllocation SowAllocationDataOnDemand.getSpecificSowAllocation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SowAllocation obj = data.get(index);
        Long id = obj.getId();
        return SowAllocation.findSowAllocation(id);
    }
    
    public SowAllocation SowAllocationDataOnDemand.getRandomSowAllocation() {
        init();
        SowAllocation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SowAllocation.findSowAllocation(id);
    }
    
    public boolean SowAllocationDataOnDemand.modifySowAllocation(SowAllocation obj) {
        return false;
    }
    
    public void SowAllocationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SowAllocation.findSowAllocationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SowAllocation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SowAllocation>();
        for (int i = 0; i < 10; i++) {
            SowAllocation obj = getNewTransientSowAllocation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
