// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.Sow;
import com.tuc.capacity.entity.SowDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SowDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SowDataOnDemand: @Component;
    
    private Random SowDataOnDemand.rnd = new SecureRandom();
    
    private List<Sow> SowDataOnDemand.data;
    
    public Sow SowDataOnDemand.getNewTransientSow(int index) {
        Sow obj = new Sow();
        setDescription(obj, index);
        setSowNum(obj, index);
        return obj;
    }
    
    public void SowDataOnDemand.setDescription(Sow obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void SowDataOnDemand.setSowNum(Sow obj, int index) {
        String sowNum = "sowNum_" + index;
        obj.setSowNum(sowNum);
    }
    
    public Sow SowDataOnDemand.getSpecificSow(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Sow obj = data.get(index);
        Long id = obj.getId();
        return Sow.findSow(id);
    }
    
    public Sow SowDataOnDemand.getRandomSow() {
        init();
        Sow obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Sow.findSow(id);
    }
    
    public boolean SowDataOnDemand.modifySow(Sow obj) {
        return false;
    }
    
    public void SowDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Sow.findSowEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Sow' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Sow>();
        for (int i = 0; i < 10; i++) {
            Sow obj = getNewTransientSow(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
