// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.Sow;
import com.tuc.capacity.entity.SowDataOnDemand;
import com.tuc.capacity.entity.SowIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SowIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SowIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SowIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SowIntegrationTest: @Transactional;
    
    @Autowired
    SowDataOnDemand SowIntegrationTest.dod;
    
    @Test
    public void SowIntegrationTest.testCountSows() {
        Assert.assertNotNull("Data on demand for 'Sow' failed to initialize correctly", dod.getRandomSow());
        long count = Sow.countSows();
        Assert.assertTrue("Counter for 'Sow' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SowIntegrationTest.testFindSow() {
        Sow obj = dod.getRandomSow();
        Assert.assertNotNull("Data on demand for 'Sow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sow' failed to provide an identifier", id);
        obj = Sow.findSow(id);
        Assert.assertNotNull("Find method for 'Sow' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Sow' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SowIntegrationTest.testFindAllSows() {
        Assert.assertNotNull("Data on demand for 'Sow' failed to initialize correctly", dod.getRandomSow());
        long count = Sow.countSows();
        Assert.assertTrue("Too expensive to perform a find all test for 'Sow', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Sow> result = Sow.findAllSows();
        Assert.assertNotNull("Find all method for 'Sow' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Sow' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SowIntegrationTest.testFindSowEntries() {
        Assert.assertNotNull("Data on demand for 'Sow' failed to initialize correctly", dod.getRandomSow());
        long count = Sow.countSows();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Sow> result = Sow.findSowEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Sow' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Sow' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SowIntegrationTest.testFlush() {
        Sow obj = dod.getRandomSow();
        Assert.assertNotNull("Data on demand for 'Sow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sow' failed to provide an identifier", id);
        obj = Sow.findSow(id);
        Assert.assertNotNull("Find method for 'Sow' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySow(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Sow' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SowIntegrationTest.testMergeUpdate() {
        Sow obj = dod.getRandomSow();
        Assert.assertNotNull("Data on demand for 'Sow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sow' failed to provide an identifier", id);
        obj = Sow.findSow(id);
        boolean modified =  dod.modifySow(obj);
        Integer currentVersion = obj.getVersion();
        Sow merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Sow' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SowIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Sow' failed to initialize correctly", dod.getRandomSow());
        Sow obj = dod.getNewTransientSow(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Sow' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Sow' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Sow' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SowIntegrationTest.testRemove() {
        Sow obj = dod.getRandomSow();
        Assert.assertNotNull("Data on demand for 'Sow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sow' failed to provide an identifier", id);
        obj = Sow.findSow(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Sow' with identifier '" + id + "'", Sow.findSow(id));
    }
    
}
