// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.SowIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SowIntegrationTest_Roo_Configurable {
    
    declare @type: SowIntegrationTest: @Configurable;
    
}
