// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.TuLead;
import com.tuc.capacity.entity.TuLeadDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TuLeadDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TuLeadDataOnDemand: @Component;
    
    private Random TuLeadDataOnDemand.rnd = new SecureRandom();
    
    private List<TuLead> TuLeadDataOnDemand.data;
    
    public TuLead TuLeadDataOnDemand.getNewTransientTuLead(int index) {
        TuLead obj = new TuLead();
        setName(obj, index);
        return obj;
    }
    
    public void TuLeadDataOnDemand.setName(TuLead obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public TuLead TuLeadDataOnDemand.getSpecificTuLead(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TuLead obj = data.get(index);
        Long id = obj.getId();
        return TuLead.findTuLead(id);
    }
    
    public TuLead TuLeadDataOnDemand.getRandomTuLead() {
        init();
        TuLead obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TuLead.findTuLead(id);
    }
    
    public boolean TuLeadDataOnDemand.modifyTuLead(TuLead obj) {
        return false;
    }
    
    public void TuLeadDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TuLead.findTuLeadEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TuLead' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TuLead>();
        for (int i = 0; i < 10; i++) {
            TuLead obj = getNewTransientTuLead(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
