// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tuc.capacity.entity;

import com.tuc.capacity.entity.TuLead;
import com.tuc.capacity.entity.TuLeadDataOnDemand;
import com.tuc.capacity.entity.TuLeadIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TuLeadIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TuLeadIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TuLeadIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TuLeadIntegrationTest: @Transactional;
    
    @Autowired
    TuLeadDataOnDemand TuLeadIntegrationTest.dod;
    
    @Test
    public void TuLeadIntegrationTest.testCountTuLeads() {
        Assert.assertNotNull("Data on demand for 'TuLead' failed to initialize correctly", dod.getRandomTuLead());
        long count = TuLead.countTuLeads();
        Assert.assertTrue("Counter for 'TuLead' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TuLeadIntegrationTest.testFindTuLead() {
        TuLead obj = dod.getRandomTuLead();
        Assert.assertNotNull("Data on demand for 'TuLead' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TuLead' failed to provide an identifier", id);
        obj = TuLead.findTuLead(id);
        Assert.assertNotNull("Find method for 'TuLead' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TuLead' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TuLeadIntegrationTest.testFindAllTuLeads() {
        Assert.assertNotNull("Data on demand for 'TuLead' failed to initialize correctly", dod.getRandomTuLead());
        long count = TuLead.countTuLeads();
        Assert.assertTrue("Too expensive to perform a find all test for 'TuLead', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TuLead> result = TuLead.findAllTuLeads();
        Assert.assertNotNull("Find all method for 'TuLead' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TuLead' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TuLeadIntegrationTest.testFindTuLeadEntries() {
        Assert.assertNotNull("Data on demand for 'TuLead' failed to initialize correctly", dod.getRandomTuLead());
        long count = TuLead.countTuLeads();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TuLead> result = TuLead.findTuLeadEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TuLead' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TuLead' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TuLeadIntegrationTest.testFlush() {
        TuLead obj = dod.getRandomTuLead();
        Assert.assertNotNull("Data on demand for 'TuLead' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TuLead' failed to provide an identifier", id);
        obj = TuLead.findTuLead(id);
        Assert.assertNotNull("Find method for 'TuLead' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTuLead(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TuLead' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TuLeadIntegrationTest.testMergeUpdate() {
        TuLead obj = dod.getRandomTuLead();
        Assert.assertNotNull("Data on demand for 'TuLead' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TuLead' failed to provide an identifier", id);
        obj = TuLead.findTuLead(id);
        boolean modified =  dod.modifyTuLead(obj);
        Integer currentVersion = obj.getVersion();
        TuLead merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TuLead' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TuLeadIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TuLead' failed to initialize correctly", dod.getRandomTuLead());
        TuLead obj = dod.getNewTransientTuLead(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TuLead' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TuLead' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TuLead' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TuLeadIntegrationTest.testRemove() {
        TuLead obj = dod.getRandomTuLead();
        Assert.assertNotNull("Data on demand for 'TuLead' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TuLead' failed to provide an identifier", id);
        obj = TuLead.findTuLead(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TuLead' with identifier '" + id + "'", TuLead.findTuLead(id));
    }
    
}
